a = [{'accountId': 36364,
     'bareMetalInstanceFlag': 0,
     'datacenter': {'id': 3, 'longName': 'Dallas', 'name': 'dal01'},
     'domain': 'playdom.com',
     'fullyQualifiedDomainName': 'alert-mta-02.playdom.com',
     'hardwareStatusId': 5,
     'hostname': 'alert-mta-02',
     'id': 102434,
     'manufacturerSerialNumber': 'C81500A17L11083',
     'networkComponents': [{'hardwareId': 102434,
                            'id': 598043,
                            'ipmiIpAddress': '10.37.12.16',
                            'ipmiMacAddress': '02:25:90:35:dd:32',
                            'maxSpeed': 1000,
                            'modifyDate': '2011-08-15T22:43:41-08:00',
                            'name': 'mgmt',
                            'networkVlanId': '',
                            'port': 0,
                            'speed': 1000,
                            'status': 'ACTIVE'},
             {'hardwareId': 102434,
              'id': 598044,
              'macAddress': '00:25:90:35:dd:32',
              'maxSpeed': 1000,
              'modifyDate': '2011-08-15T22:43:38-08:00',
              'name': 'eth',
              'networkVlanId': '',
              'port': 0,
              'primaryIpAddress': '10.37.12.15',
              'speed': 1000,
              'status': 'ACTIVE'},
             {'hardwareId': 102434,
              'id': 598045,
              'macAddress': '00:25:90:35:dd:33',
              'maxSpeed': 1000,
              'modifyDate': '2011-08-15T22:43:30-08:00',
              'name': 'eth',
              'networkVlanId': '',
              'port': 1,
              'primaryIpAddress': '75.126.118.17',
              'speed': 1000,
              'status': 'ACTIVE'}],
     'networkManagementIpAddress': '10.37.12.16',
     'notes': '[Ops:App:2011-11-15]',
     'operatingSystem': {'hardwareId': 102434,
                         'id': 841656,
                         'manufacturerLicenseInstance': '',
                         'passwords': [{'createDate': '2012-02-14T15:32:42-08:00',
                                        'id': 943133,
                                        'modifyDate': '2012-02-14T15:32:42-08:00',
                                        'password': 'blahblah',
                                        'port': '',
                                        'softwareId': 841656,
                                        'username': 'root'},
                                 {'createDate': '2012-02-14T15:32:42-08:00',
                                  'id': 943134,
                                  'modifyDate': '2012-02-14T15:32:42-08:00',
                                  'password': 'blahasdf!',
                                  'port': '',
                                  'softwareId': 841656,
                                  'username': 'softlayer'}],
                         'softwareLicense': {'id': 777,
                                             'softwareDescription': {'controlPanel': 0,
                                                                     'id': 775,
                                                                     'manufacturer': 'Ubuntu',
                                                                     'name': 'Ubuntu',
                                                                     'operatingSystem': 1,
                                                                     'requiredUser': 'root',
                                                                     'upgradeSoftwareDescriptionId': '',
                                                                     'upgradeSwDescId': '',
                                                                     'version': '10.04.1-64',
                                                                     'virtualLicense': 0,
                                                                     'virtualizationPlatform': 0},
                                             'softwareDescriptionId': 775}},
     'primaryBackendIpAddress': '10.37.12.15',
     'primaryIpAddress': '75.126.118.17',
     'privateIpAddress': '10.37.12.15',
     'processorCount': 2,
     'serialNumber': 'SL0039617',
     'serviceProviderId': 1,
     'serviceProviderResourceId': 102434}]

for eachDev in a:
    ip=""
    hostname=""
    loc=""
    if ("privateIpAddress" in eachDev.keys()):
        ip=eachDev["privateIpAddress"]
    if ("hostname" in eachDev.keys()):
        hostname=eachDev["hostname"]
    if ("datacenter" in eachDev.keys()):
        loc=eachDev["datacenter"]
    print "IP: %s, HOSTNAME: %s, LOCATION: %s" % (ip,hostname,loc)